### PR TITLE
Create Top_K_Frequent.cpp

### PR DESCRIPTION
**Pull request by abhisek247767**
Added.

### CODE REVIEW

**Review by AnujitSingh — COMMENTED** [review]
Hi there, please check your code for errors.

**Comment by abhisek247767** [comment]
This is gfg question. So It's main algorithm code with 8 different method. Hope you understand what i tiring to say

**Comment by AnujitSingh** [comment]
So please rename it so that people could understand better what this code is all about.

**Comment by abhisek247767** [comment]
Now check. And let me confirmed.

**Pull request merged**
